#os:
#    - windows
#    - linux

language: cpp

matrix:
    include:
        - os: linux
        - os: windows
          env: 
          - MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
          - OS="$TRAVIS_OS_NAME"
env: OS="$TRAVIS_OS_NAME"
addons:
  apt:
    packages:
    - python-serial
    - srecord
cache:
  - directories:
    - cache
script:
- echo OS is $OS $TRAVIS_OS_NAME
- if [ "$OS" = "linux" ]; then export BUILD_DATE=$(date +%Y%m%d); fi
- if [ "$OS" = "linux" ]; then make EXTRA_CCFLAGS="-DLUA_NUMBER_INTEGRAL -DBUILD_DATE='\"'$BUILD_DATE'\"'"; fi
- if [ "$OS" = "linux" ]; then cd bin/; fi
- if [ "$OS" = "linux" ]; then file_name_integer="nodemcu_integer_${TRAVIS_TAG}.bin"; fi
- if [ "$OS" = "linux" ]; then srec_cat -output ${file_name_integer} -binary 0x00000.bin -binary -fill 0xff 0x00000 0x10000 0x10000.bin -binary -offset 0x10000; fi
- if [ "$OS" = "linux" ]; then cd ../; fi
- if [ "$OS" = "linux" ]; then make clean; fi
- if [ "$OS" = "linux" ]; then make EXTRA_CCFLAGS="-DBUILD_DATE='\"'$BUILD_DATE'\"'" all; fi
- if [ "$OS" = "linux" ]; then cd bin/; fi
- if [ "$OS" = "linux" ]; then file_name_float="nodemcu_float_${TRAVIS_TAG}.bin"; fi
- if [ "$OS" = "linux" ]; then srec_cat -output ${file_name_float} -binary 0x00000.bin -binary -fill 0xff 0x00000 0x10000 0x10000.bin -binary -offset 0x10000; fi
- if [ "$OS" = "linux" ]; then LUACC=./luac.cross; fi
# http://docs.travis-ci.com/user/environment-variables/#Convenience-Variables
- if [ "$OS" = "linux" -a "$TRAVIS_PULL_REQUEST" != "false" ]; then bash "$TRAVIS_BUILD_DIR"/tools/pr-build.sh; fi
- if [ "$OS" = "windows" ]; then cd "$TRAVIS_BUILD_DIR"/msvc; fi
- if [ "$OS" = "windows" ]; then ls -la; fi
- if [ "$OS" = "windows" ]; then export PATH=$MSBUILD_PATH:$PATH; fi
- if [ "$OS" = "windows" ]; then msbuild.exe hosttools.sln; fi
- if [ "$OS" = "windows" ]; then LUACC=msvc/luac-cross/x64/Debug/luac.cross.exe; fi
- cd "$TRAVIS_BUILD_DIR"
- LUA_FILES=`find lua_modules lua_examples -iname "*.lua"`
- echo checking $LUA_FILES
- $LUACC -p $LUA_FILES
